name = "qr-redirect-worker"
type = "javascript"  # hoặc "webpack" nếu dùng bundler cũ
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = false

routes = [
  "https://tpbc.top/*"
]

compatibility_date = "2025-08-01"
